# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  docs:
    docker:
    - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build
      #- run: git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_OAUTH_TOKEN}:@github.com" > .git/credentials 2>/dev/null
      - run: git config --global user.email "alexanmtz@gmail.com"
      - run: git config --global user.name "Alexandre Magno"
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              git pull origin master && git add . && git commit -m 'build page [ci skip]' --allow-empty && git push origin master
            fi
    environment:
      GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN}

workflows:
  version: 2
  build-all:
    jobs:
      - docs:
          filters:
            branches:
              only: master
